### PR TITLE
Create Makefile

### PR DESCRIPTION
**Pull request by julietsampson**

### CODE REVIEW

**Comment by mandli** [comment]
Can we close #43, #44, #45, and #46 in lieu of this PR?

**Comment by julietsampson** [comment]
Oh yeah, sorry, I wasn’t sure how to pull request properly! My apologies.

Best,

Juliet Sampson

**Comment by mandli** [comment]
If you can close the PRs that are not relevant that would be helpful.

**Comment by mandli** [comment]
Just add the `setrun.py`, `setplot.py` and `readme.md` then to this branch and the PR will update.

**Comment by julietsampson** [comment]
Okay sorry I will do that! This week has been kinda hectic, apologies for
not doing that sooner.

**Comment by mandli** [comment]
@julietsampson can you add more to the readme?

**Pull request merged**
